/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.exathunk.genthrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * A container type
 */
public enum ContType implements org.apache.thrift.TEnum {
  VOID(0),
  SINGLETON(1),
  LIST(2),
  SET(3),
  MAP(4);

  private final int value;

  private ContType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ContType findByValue(int value) { 
    switch (value) {
      case 0:
        return VOID;
      case 1:
        return SINGLETON;
      case 2:
        return LIST;
      case 3:
        return SET;
      case 4:
        return MAP;
      default:
        return null;
    }
  }
}
