/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.exathunk.genthrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Strictness implements org.apache.thrift.TEnum {
  STRICT(0),
  LENIENT(1),
  LAZY(2);

  private final int value;

  private Strictness(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Strictness findByValue(int value) { 
    switch (value) {
      case 0:
        return STRICT;
      case 1:
        return LENIENT;
      case 2:
        return LAZY;
      default:
        return null;
    }
  }
}
