/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.exathunk.genthrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A tree of VarConts, to be accompanied by a VarTreeType.
 * Because Thrift does not natively support recursive types,
 * we have to use indices in a list to address children.
 */
public class VarTree implements org.apache.thrift.TBase<VarTree, VarTree._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("VarTree");

  private static final org.apache.thrift.protocol.TField NODES_FIELD_DESC = new org.apache.thrift.protocol.TField("nodes", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField ROOT_INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("rootIndex", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new VarTreeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new VarTreeTupleSchemeFactory());
  }

  private List<VarTreeNode> nodes; // required
  private int rootIndex; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NODES((short)1, "nodes"),
    ROOT_INDEX((short)2, "rootIndex");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NODES
          return NODES;
        case 2: // ROOT_INDEX
          return ROOT_INDEX;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ROOTINDEX_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NODES, new org.apache.thrift.meta_data.FieldMetaData("nodes", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, VarTreeNode.class))));
    tmpMap.put(_Fields.ROOT_INDEX, new org.apache.thrift.meta_data.FieldMetaData("rootIndex", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(VarTree.class, metaDataMap);
  }

  public VarTree() {
  }

  public VarTree(
    List<VarTreeNode> nodes,
    int rootIndex)
  {
    this();
    this.nodes = nodes;
    this.rootIndex = rootIndex;
    setRootIndexIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public VarTree(VarTree other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetNodes()) {
      List<VarTreeNode> __this__nodes = new ArrayList<VarTreeNode>();
      for (VarTreeNode other_element : other.nodes) {
        __this__nodes.add(new VarTreeNode(other_element));
      }
      this.nodes = __this__nodes;
    }
    this.rootIndex = other.rootIndex;
  }

  public VarTree deepCopy() {
    return new VarTree(this);
  }

  @Override
  public void clear() {
    this.nodes = null;
    setRootIndexIsSet(false);
    this.rootIndex = 0;
  }

  public int getNodesSize() {
    return (this.nodes == null) ? 0 : this.nodes.size();
  }

  public java.util.Iterator<VarTreeNode> getNodesIterator() {
    return (this.nodes == null) ? null : this.nodes.iterator();
  }

  public void addToNodes(VarTreeNode elem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<VarTreeNode>();
    }
    this.nodes.add(elem);
  }

  public List<VarTreeNode> getNodes() {
    return this.nodes;
  }

  public void setNodes(List<VarTreeNode> nodes) {
    this.nodes = nodes;
  }

  public void unsetNodes() {
    this.nodes = null;
  }

  /** Returns true if field nodes is set (has been assigned a value) and false otherwise */
  public boolean isSetNodes() {
    return this.nodes != null;
  }

  public void setNodesIsSet(boolean value) {
    if (!value) {
      this.nodes = null;
    }
  }

  public int getRootIndex() {
    return this.rootIndex;
  }

  public void setRootIndex(int rootIndex) {
    this.rootIndex = rootIndex;
    setRootIndexIsSet(true);
  }

  public void unsetRootIndex() {
    __isset_bit_vector.clear(__ROOTINDEX_ISSET_ID);
  }

  /** Returns true if field rootIndex is set (has been assigned a value) and false otherwise */
  public boolean isSetRootIndex() {
    return __isset_bit_vector.get(__ROOTINDEX_ISSET_ID);
  }

  public void setRootIndexIsSet(boolean value) {
    __isset_bit_vector.set(__ROOTINDEX_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NODES:
      if (value == null) {
        unsetNodes();
      } else {
        setNodes((List<VarTreeNode>)value);
      }
      break;

    case ROOT_INDEX:
      if (value == null) {
        unsetRootIndex();
      } else {
        setRootIndex((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NODES:
      return getNodes();

    case ROOT_INDEX:
      return Integer.valueOf(getRootIndex());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NODES:
      return isSetNodes();
    case ROOT_INDEX:
      return isSetRootIndex();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof VarTree)
      return this.equals((VarTree)that);
    return false;
  }

  public boolean equals(VarTree that) {
    if (that == null)
      return false;

    boolean this_present_nodes = true && this.isSetNodes();
    boolean that_present_nodes = true && that.isSetNodes();
    if (this_present_nodes || that_present_nodes) {
      if (!(this_present_nodes && that_present_nodes))
        return false;
      if (!this.nodes.equals(that.nodes))
        return false;
    }

    boolean this_present_rootIndex = true;
    boolean that_present_rootIndex = true;
    if (this_present_rootIndex || that_present_rootIndex) {
      if (!(this_present_rootIndex && that_present_rootIndex))
        return false;
      if (this.rootIndex != that.rootIndex)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(VarTree other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    VarTree typedOther = (VarTree)other;

    lastComparison = Boolean.valueOf(isSetNodes()).compareTo(typedOther.isSetNodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNodes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nodes, typedOther.nodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRootIndex()).compareTo(typedOther.isSetRootIndex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRootIndex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rootIndex, typedOther.rootIndex);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("VarTree(");
    boolean first = true;

    sb.append("nodes:");
    if (this.nodes == null) {
      sb.append("null");
    } else {
      sb.append(this.nodes);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rootIndex:");
    sb.append(this.rootIndex);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetNodes()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'nodes' is unset! Struct:" + toString());
    }

    if (!isSetRootIndex()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'rootIndex' is unset! Struct:" + toString());
    }

  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VarTreeStandardSchemeFactory implements SchemeFactory {
    public VarTreeStandardScheme getScheme() {
      return new VarTreeStandardScheme();
    }
  }

  private static class VarTreeStandardScheme extends StandardScheme<VarTree> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, VarTree struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NODES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list34 = iprot.readListBegin();
                struct.nodes = new ArrayList<VarTreeNode>(_list34.size);
                for (int _i35 = 0; _i35 < _list34.size; ++_i35)
                {
                  VarTreeNode _elem36; // required
                  _elem36 = new VarTreeNode();
                  _elem36.read(iprot);
                  struct.nodes.add(_elem36);
                }
                iprot.readListEnd();
              }
              struct.setNodesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ROOT_INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.rootIndex = iprot.readI32();
              struct.setRootIndexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, VarTree struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.nodes != null) {
        oprot.writeFieldBegin(NODES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.nodes.size()));
          for (VarTreeNode _iter37 : struct.nodes)
          {
            _iter37.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ROOT_INDEX_FIELD_DESC);
      oprot.writeI32(struct.rootIndex);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VarTreeTupleSchemeFactory implements SchemeFactory {
    public VarTreeTupleScheme getScheme() {
      return new VarTreeTupleScheme();
    }
  }

  private static class VarTreeTupleScheme extends TupleScheme<VarTree> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, VarTree struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.nodes.size());
        for (VarTreeNode _iter38 : struct.nodes)
        {
          _iter38.write(oprot);
        }
      }
      oprot.writeI32(struct.rootIndex);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, VarTree struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list39 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.nodes = new ArrayList<VarTreeNode>(_list39.size);
        for (int _i40 = 0; _i40 < _list39.size; ++_i40)
        {
          VarTreeNode _elem41; // required
          _elem41 = new VarTreeNode();
          _elem41.read(iprot);
          struct.nodes.add(_elem41);
        }
      }
      struct.setNodesIsSet(true);
      struct.rootIndex = iprot.readI32();
      struct.setRootIndexIsSet(true);
    }
  }

}

